# Generated by Django 5.1.6 on 2025-02-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_review_movie_moviesreviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesreviews',
            name='reviews',
        ),
        migrations.AddField(
            model_name='moviesreviews',
            name='reviews',
            field=models.ManyToManyField(to='movie_app.review'),
        ),
    ]
