# Generated by Django 5.1.6 on 2025-02-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_moviesreviews_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMoviesSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.director')),
                ('movies', models.ManyToManyField(blank=True, to='movie_app.movie')),
            ],
        ),
    ]
