# Generated by Django 5.1.6 on 2025-02-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_directormoviesserializer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectorMoviesSerializer',
            new_name='DirectorMovies',
        ),
    ]
